# TUTORIAL
# Edit this file then run this command in the root directory
# zensical build --clean  
#
# When done, a "site" folder should appear
# To start the server, run the command:
# python -m http.server 8000 --directory .\site
#
# The documentation can be seen by going on chrome :
# http://localhost:8000/

# ressources :
# https://gist.github.com/rxaviers/7360908

[project]
site_name = "Lucent"
site_description = "Lucent is a system for defining, validating, and resolving naming conventions."
site_url = "https://tristanlanguebien.github.io/lucent/"
repo_url = "https://github.com/tristanlanguebien/lucent"
repo_name = "tristanlanguebien/lucent"
edit_uri = "edit/main/docs/" # ??
extra_css = ["stylesheets/extra.css"]
nav = [
    { "Home" = "index.md" },
    { "Installation" = "installation.md" },
    { "Configuration" = "configuration.md" },
    { "Usage" = "usage.md" },
    { "Lucent Watcher" = "watcher.md" },
    { "Glossary" = "glossary.md" },
    { "Acknowledgments" = "acknowledgments.md" },
    { "Code Reference" = [
        {"Codex" = "reference_codex.md"},
        {"Convention" = "reference_convention.md"},
        {"Conventions" = "reference_conventions.md"},
        {"Rule" = "reference_rule.md"},
        {"Rules" = "reference_rules.md"}
    ]},
]

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/moon-star"
toggle.name = ""

[project.theme]
features = [
    "navigation.sections",
    "navigation.top",
    "search.suggest",
    "search.highlight",
    "content.tabs.link",
    "content.code.annotation",
    "content.code.copy",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false
docstring_section_style = "list"
# extensions = []
group_by_category = true
heading_level = 2
members_order = "alphabetical"
merge_init_into_class = false
modernize_annotations = true
parameter_headings = false
separate_signature = true
show_category_heading = true
show_docstring_attributes = false
show_docstring_parameters = true
show_docstring_returns = true
show_if_no_docstring = true
show_labels = false
show_root_full_path = false
show_root_heading = true
show_root_toc_entry = false
show_signature_annotations = true
show_signature = true
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
relative_crossrefs = true
scoped_crossrefs = true
filters = ["!^_"]

